### ISSUE TITLE
Re-accessing locked data slots

### ISSUE THREAD

**Issue by ghost** [Infineon/optiga-trust-x#49] opened 2022-08-10 07:46 UTC
Hi,

We're currently saving sensitive data into the Trust X chip and locking the slot, preventing read and write operations, but we have to change the data inside several already locked chips in the future. We read that the LCS state isn't reversible, but are there any operations that can be done so that we can re-access the data slots?

Thanks

**Comment by sss551** [comment] 2022-08-10 08:35
Hi @EnkyuuBi,

Thank you for contacting us.
Yes, the Lcso state is not reversible. Protected Update of the objects is not supported in the Trust X chip. So, there is no way to re-access the data slots. For your information, Optiga Trust M allows to re-access the data object via Protected Data Update.

Thanks

**Comment by sss551** [comment] 2022-09-27 04:21
Hi @EnkyuuBi,

Can you please let us know whether the issue is resolved. If yes, please close the issue.

Thanks

**Closed as completed** 2022-10-03 04:00 UTC
